name: encrypt
version: 4.1.0
description: A set of high-level APIs over PointyCastle for two-way cryptography.
author: leocavalcante <lc@leocavalcante.com>
homepage: https://github.com/leocavalcante/encrypt

executables:
  secure-random:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  args: ^1.6.0 # dart.dev
  asn1lib: # ^0.8.1 - DONE: Secure code reviewed e3589be
    git:
      url: git://github.com/KomodoPlatform/asn1lib.git
      ref: e3589be96f730ac1ca25b9bbdfd40138a79e2f3a
  clock: # ^1.0.1 DONE: Secure code reviewed 6210621
    git:
      url: git://github.com/KomodoPlatform/clock.git
      ref: b703d0c4fed4c57ac4d2c0637b2b34474d22e14a
  collection: ^1.14.13 # dart.dev
  crypto: ^2.1.5 # dart.dev
  pointycastle: # ^2.0.0 TODO/work in pro: Secure code review 162a6ac
    git:
      url: git://github.com/KomodoPlatform/pc-dart.git
      ref: 162a6ac2b75c693ffa30cd2e4ff26757c91e988d

dev_dependencies:
  test: ^1.15.4 # dart.dev
