name: encrypt
version: 4.1.0
description: A set of high-level APIs over PointyCastle for two-way cryptography.
author: leocavalcante <lc@leocavalcante.com>
homepage: https://github.com/leocavalcante/encrypt

executables:
  secure-random:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  args: ^1.6.0 # dart.dev
  asn1lib: ^0.8.1 # https://github.com/KomodoPlatform/asn1lib - TODO: sec review
  clock: ^1.0.1 # https://github.com/KomodoPlatform/clock - TODO: sec review
  collection: ^1.14.13 # dart.dev
  crypto: ^2.1.5 # dart.dev
  pointycastle: ^2.0.0 # https://github.com/KomodoPlatform/pc-dart - TODO: sec review - published by bouncycastle.org (verified)

dev_dependencies:
  test: ^1.15.4 # dart.dev
