name: encrypt
version: 4.0.3
description: A set of high-level APIs over PointyCastle for two-way cryptography.
author: leocavalcante <lc@leocavalcante.com>
homepage: https://github.com/leocavalcante/encrypt

executables:
  secure-random:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  args: ^1.6.0
  asn1lib: # ^0.6.4 - DONE: Secure code reviewed 1f5e2f2
    git:
      url: git://github.com/KomodoPlatform/asn1lib.git
      ref: 1f5e2f2d0d4543456880962ebf5adc5dcd30082d
  clock: ^1.0.1 # dart.dev
  collection: ^1.14.12
  crypto: ^2.1.4
  pointycastle: # ^1.0.2 DONE: Secure code reviewed d106a92
    git:
      url: git://github.com/KomodoPlatform/pc-dart.git
      ref: d106a9218a9df81ef4e0ab239ce5db2fcd9a7435

dev_dependencies:
  test: ^1.14.3
